In [1]:
import pandas as pd

df = pd.DataFrame({
    "Order_ID": [101,102,103,104,105,106,107,108,109,110],
    "Customer": ["Alice","Bob","Alice","Charlie","Bob","David","Alice","Charlie","David","Bob"],
    "Category": ["Electronics","Clothing","Electronics","Furniture","Electronics",
                 "Clothing","Furniture","Electronics","Furniture","Clothing"],
    "City": ["Mumbai","Delhi","Mumbai","Pune","Delhi",
             "Mumbai","Pune","Delhi","Mumbai","Pune"],
    "Quantity": [2,5,1,3,4,2,1,6,2,3],
    "Price": [50000,1500,70000,12000,45000,2000,10000,30000,15000,2500],
    "Year": [2024,2024,2025,2025,2024,2025,2024,2025,2025,2024]
})

print(df)

   Order_ID Customer     Category    City  Quantity  Price  Year
0       101    Alice  Electronics  Mumbai         2  50000  2024
1       102      Bob     Clothing   Delhi         5   1500  2024
2       103    Alice  Electronics  Mumbai         1  70000  2025
3       104  Charlie    Furniture    Pune         3  12000  2025
4       105      Bob  Electronics   Delhi         4  45000  2024
5       106    David     Clothing  Mumbai         2   2000  2025
6       107    Alice    Furniture    Pune         1  10000  2024
7       108  Charlie  Electronics   Delhi         6  30000  2025
8       109    David    Furniture  Mumbai         2  15000  2025
9       110      Bob     Clothing    Pune         3   2500  2024

In [2]:
df.groupby("Category")["Price"].sum()

Category
Clothing         6000
Electronics    195000
Furniture       37000
Name: Price, dtype: int64

In [3]:
df.groupby("Customer")["Quantity"].mean()

Customer
Alice      1.333333
Bob        4.000000
Charlie    4.500000
David      2.000000
Name: Quantity, dtype: float64

In [4]:
df[df["Year"] == 2025].groupby("Category")["Price"].sum()

Category
Clothing         2000
Electronics    100000
Furniture       27000
Name: Price, dtype: int64

In [5]:
df[df["Year"] == 2025].groupby("Customer")["Price"].sum().sort_values(ascending=False).head(1)

Customer
Alice    70000
Name: Price, dtype: int64

In [6]:
df[df["Year"] == 2024].groupby("Customer")["Price"].sum().sort_values(ascending=False).head(2)

Customer
Alice    60000
Bob      49000
Name: Price, dtype: int64

In [7]:
df.groupby("Category").agg(
    Total_Price = ("Price", "sum"),
    Average_Quantity = ("Quantity", "mean")
)

             Total_Price  Average_Quantity
Category
Clothing            6000          3.333333
Electronics       195000          3.250000
Furniture          37000          2.000000

In [8]:
df[df["Year"] == 2025].groupby("Category")["Price"].sum().sort_values(ascending=False).reset_index(name="Total_Price")

      Category  Total_Price
0  Electronics       100000
1    Furniture        27000
2     Clothing         2000

In [9]:
df.groupby("Customer").agg(
    Total_Price = ("Price", "sum"),
    Total_Quantity = ("Quantity", "sum"),
    Avg_Price = ("Price", "mean")
)

          Total_Price  Total_Quantity     Avg_Price
Customer
Alice          130000               4  43333.333333
Bob             49000              12  16333.333333
Charlie         42000               9  21000.000000
David           17000               4   8500.000000

In [10]:
df.groupby("Customer")["Quantity"].sum().where(df["Quantity"] > 1)

Customer
Alice     NaN
Bob       NaN
Charlie   NaN
David     NaN
Name: Quantity, dtype: float64

In [11]:
df.groupby("Customer")["Order_ID"].count()

Customer
Alice      3
Bob        3
Charlie    2
David      2
Name: Order_ID, dtype: int64

In [12]:
df.groupby("Category")["Customer"].unique().reset_index(name="Unique_Customers")

      Category         Unique_Customers
0     Clothing             [Bob, David]
1  Electronics    [Alice, Bob, Charlie]
2    Furniture  [Charlie, Alice, David]

In [13]:
df.groupby("City")["Order_ID"].count().reset_index(name="Order_Count")

     City  Order_Count
0   Delhi            3
1  Mumbai            4
2    Pune            3

In [14]:
df[(df["Category"] == "Electronics") & (df["Year"] == 2025)].groupby("Category")["Price"].sum().reset_index(name="Total_Price")

      Category  Total_Price
0  Electronics       100000

In [15]:
df.groupby(["Category", "City"])["Price"].sum().reset_index(name="Total_Price")

      Category    City  Total_Price
0     Clothing   Delhi         1500
1     Clothing  Mumbai         2000
2     Clothing    Pune         2500
3  Electronics   Delhi        75000
4  Electronics  Mumbai       120000
5    Furniture  Mumbai        15000
6    Furniture    Pune        22000

In [16]:
df.groupby("City")["Quantity"].sum().head(2).reset_index(name="Sales")

     City  Sales
0   Delhi     15
1  Mumbai      7

In [17]:
df.groupby("City").agg(
    Total_Price = ("Price", "sum"),
    Average_Price = ("Price", "mean"),
    Maximum_Quantity = ("Quantity", "max"),
    Number_of_Orders = ("Order_ID", "count")
)

        Total_Price  Average_Price  Maximum_Quantity  Number_of_Orders
City
Delhi         76500   25500.000000                 6                 3
Mumbai       137000   34250.000000                 2                 4
Pune          24500    8166.666667                 3                 3

In [18]:
df.groupby("Customer")["Order_ID"].count().sort_values(ascending=False).head(1)

Customer
Alice    3
Name: Order_ID, dtype: int64

In [19]:
df.groupby("Category")["Price"].sum().sort_values(ascending=False).head(1)

Category
Electronics    195000
Name: Price, dtype: int64

In [20]:
df.groupby("City")["Order_ID"].count().sort_values(ascending=False).head(1)

City
Mumbai    4
Name: Order_ID, dtype: int64

In [21]:
result = df.groupby("Customer")["Category"].nunique().reset_index(name="Category_Count")
result[result["Category_Count"] > 1]

  Customer  Category_Count
0    Alice               2
1      Bob               2
2  Charlie               2
3    David               2

In [22]:
result = df.groupby("Customer")["Price"].sum().reset_index(name="Total_Spent")
result[result["Total_Spent"] > 50000]

  Customer  Total_Spent
0    Alice       130000

In [23]:
filtered_df = df.groupby("Customer")["Price"].sum().loc[lambda x: x > 50000].index
df[df["Customer"].isin(filtered_df)]

   Order_ID Customer     Category    City  Quantity  Price  Year
0       101    Alice  Electronics  Mumbai         2  50000  2024
2       103    Alice  Electronics  Mumbai         1  70000  2025
6       107    Alice    Furniture    Pune         1  10000  2024

In [24]:
df[df["Price"] == df["Price"].max()]["Customer"]
df.iloc[df["Price"].idxmax()]
df.sort_values("Price", ascending=False).head(1)

   Order_ID Customer     Category    City  Quantity  Price  Year
2       103    Alice  Electronics  Mumbai         1  70000  2025

In [25]:
result = df.groupby("Category").agg(
    Total_Price=("Price", "sum"),
    Avg_Quantity=("Quantity", "mean")
)

result[
    (result["Total_Price"] > 50000) &
    (result["Avg_Quantity"] > 2)
]

             Total_Price  Avg_Quantity
Category
Electronics       195000          3.25

In [26]:
filtered_df = df.groupby("City")["Price"].max().values
df[df["Price"].isin(filtered_df)]["Customer"]

2      Alice
3    Charlie
4        Bob
Name: Customer, dtype: str

In [27]:
sec_highest_order = [df["Price"].sort_values(ascending=False).iloc[1]]
df[df["Price"].isin(sec_highest_order)]

   Order_ID Customer     Category    City  Quantity  Price  Year
0       101    Alice  Electronics  Mumbai         2  50000  2024

In [28]:
df.groupby("Customer")["Price"].mean().loc[lambda x: x > 30000]

Customer
Alice    43333.333333
Name: Price, dtype: float64

In [29]:
df[df["Year"] == 2025].groupby("City")["Price"].sum().idxmax()

'Mumbai'

In [30]:
df[df["Customer"] == df.groupby("Customer")["Price"].sum().idxmax()]

   Order_ID Customer     Category    City  Quantity  Price  Year
0       101    Alice  Electronics  Mumbai         2  50000  2024
2       103    Alice  Electronics  Mumbai         1  70000  2025
6       107    Alice    Furniture    Pune         1  10000  2024

In [31]:
df.groupby("Category")

In [32]:
df.groupby(["Customer", "Category"])["Price"].pct_change() * 100

0          NaN
1          NaN
2    40.000000
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8          NaN
9    66.666667
Name: Price, dtype: float64

In [33]:
order_count = df.groupby("Customer")["Order_ID"].count()
customers = order_count[order_count >= 2].index

filtered = df[df["Customer"].isin(customers)]

In [34]:
import pandas as pd

df = pd.DataFrame({
    "listing_id": range(101, 141),

    "host_id": [
        1,1,1,1,
        2,2,2,2,
        3,3,3,3,
        4,4,4,4,
        5,5,5,5,
        6,6,6,6,
        7,7,7,7,
        8,8,8,8,
        9,9,9,9,
        10,10,10,10
    ],

    "host_is_superhost": [
        "t","t","t","t",
        "f","f","f","f",
        "t","t","t","t",
        "f","f","f","f",
        "t","t","t","t",
        "f","f","f","f",
        "t","t","t","t",
        "f","f","f","f",
        "t","t","t","t",
        "f","f","f","f"
    ],

    "neighbourhood_cleansed": [

        # Host 1 (Professional)
        "Downtown","Beach","Suburb","Old Town",

        # Host 2
        "Downtown","Downtown","Beach","Beach",

        # Host 3 (Professional)
        "Downtown","Beach","Suburb","Old Town",

        # Host 4
        "Suburb","Suburb","Suburb","Old Town",

        # Host 5 (Professional)
        "Downtown","Beach","Suburb","Old Town",

        # Host 6
        "Beach","Beach","Beach","Suburb",

        # Host 7 (Professional)
        "Downtown","Beach","Suburb","Old Town",

        # Host 8
        "Old Town","Old Town","Old Town","Downtown",

        # Host 9 (Professional)
        "Downtown","Beach","Suburb","Old Town",

        # Host10
        "Suburb","Beach","Beach","Beach"
    ],

    "price":[
        210,220,240,260,
        120,130,150,160,
        420,410,430,450,
        180,170,175,185,
        310,320,330,340,
        140,150,155,160,
        510,520,500,540,
        130,120,125,135,
        380,390,400,410,
        200,205,195,210
    ],

    "review_scores_rating":[
        98,97,98,99,
        90,89,91,92,
        99,99,98,100,
        88,87,89,90,
        97,98,97,98,
        85,86,84,85,
        100,99,99,100,
        86,87,88,87,
        98,97,98,99,
        90,91,89,90
    ],

    "review_scores_accuracy":[
        10,10,9,10,
        8,8,8,9,
        10,10,10,10,
        8,7,8,8,
        9,10,9,10,
        7,8,7,8,
        10,10,10,10,
        8,8,8,8,
        10,9,10,9,
        8,8,8,8
    ],

    "review_scores_cleanliness":[
        10,10,10,9,
        8,8,9,8,
        10,10,10,10,
        8,7,8,8,
        9,9,10,9,
        7,8,7,8,
        10,10,10,10,
        8,8,8,8,
        9,10,9,10,
        8,8,7,8
    ],

    "review_scores_checkin":[
        10,9,10,10,
        8,8,9,8,
        10,10,10,10,
        8,8,8,8,
        9,10,9,9,
        8,8,7,8,
        10,10,10,10,
        8,8,8,8,
        10,9,10,9,
        8,8,8,8
    ],

    "review_scores_communication":[
        10,10,10,9,
        8,8,8,9,
        10,10,10,10,
        8,8,7,8,
        9,10,9,10,
        7,8,7,8,
        10,10,10,10,
        8,8,8,8,
        10,10,9,10,
        8,8,8,8
    ],

    "review_scores_location":[
        10,10,10,9,
        9,8,9,8,
        10,10,10,10,
        8,8,8,8,
        10,9,10,9,
        8,8,8,8,
        10,10,10,10,
        8,8,8,8,
        10,10,9,10,
        8,8,8,8
    ],

    "review_scores_value":[
        9,9,9,9,
        8,8,8,8,
        10,9,10,10,
        8,7,8,8,
        9,9,9,10,
        7,8,7,8,
        10,10,10,10,
        8,8,8,8,
        9,9,10,9,
        8,8,8,8
    ]
})

df

,listing_id,host_id,host_is_superhost,neighbourhood_cleansed,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,101,1,t,Downtown,210,98,10,10,10,10,10,9
1,102,1,t,Beach,220,97,10,10,9,10,10,9
2,103,1,t,Suburb,240,98,9,10,10,10,10,9
3,104,1,t,Old Town,260,99,10,9,10,9,9,9
4,105,2,f,Downtown,120,90,8,8,8,8,9,8
5,106,2,f,Downtown,130,89,8,8,8,8,8,8
6,107,2,f,Beach,150,91,8,9,9,8,9,8
7,108,2,f,Beach,160,92,9,8,8,9,8,8
8,109,3,t,Downtown,420,99,10,10,10,10,10,10
9,110,3,t,Beach,410,99,10,10,10,10,10,9
10,111,3,t,Suburb,430,98,10,10,10,10,10,10
11,112,3,t,Old Town,450,100,10,10,10,10,10,10
12,113,4,f,Suburb,180,88,8,8,8,8,8,8
13,114,4,f,Suburb,170,87,7,7,8,8,8,7
14,115,4,f,Suburb,175,89,8,8,8,7,8,8
15,116,4,f,Old Town,185,90,8,8,8,8,8,8
16,117,5,t,Downtown,310,97,9,9,9,9,10,9
17,118,5,t,Beach,320,98,10,9,10,10,9,9
18,119,5,t,Suburb,330,97,9,10,9,9,10,9
19,120,5,t,Old Town,340,98,10,9,9,10,9,10
20,121,6,f,Beach,140,85,7,7,8,7,8,7
21,122,6,f,Beach,150,86,8,8,8,8,8,8
22,123,6,f,Beach,155,84,7,7,7,7,8,7
23,124,6,f,Suburb,160,85,8,8,8,8,8,8
24,125,7,t,Downtown,510,100,10,10,10,10,10,10
25,126,7,t,Beach,520,99,10,10,10,10,10,10
26,127,7,t,Suburb,500,99,10,10,10,10,10,10
27,128,7,t,Old Town,540,100,10,10,10,10,10,10
28,129,8,f,Old Town,130,86,8,8,8,8,8,8
29,130,8,f,Old Town,120,87,8,8,8,8,8,8
30,131,8,f,Old Town,125,88,8,8,8,8,8,8
31,132,8,f,Downtown,135,87,8,8,8,8,8,8
32,133,9,t,Downtown,380,98,10,9,10,10,10,9
33,134,9,t,Beach,390,97,9,10,9,10,10,9
34,135,9,t,Suburb,400,98,10,9,10,9,9,10
35,136,9,t,Old Town,410,99,9,10,9,10,10,9
36,137,10,f,Suburb,200,90,8,8,8,8,8,8
37,138,10,f,Beach,205,91,8,8,8,8,8,8
38,139,10,f,Beach,195,89,8,7,8,8,8,8
39,140,10,f,Beach,210,90,8,8,8,8,8,8

In [35]:
filtered = df.groupby(["neighbourhood_cleansed", "host_is_superhost"], as_index=False)["price"].median()
filtered = filtered.pivot(index="neighbourhood_cleansed", columns="host_is_superhost", values="price")
filtered["diff"] = filtered["t"] - filtered["f"]
filtered["diff"].idxmax()

'Old Town'

In [36]:
multi_neighbourhood_hosts = (
    df.groupby("host_id")["neighbourhood_cleansed"]
      .nunique()
)

professional_hosts = multi_neighbourhood_hosts[
    multi_neighbourhood_hosts >= 3
].index

df["professional"] = df["host_id"].isin(professional_hosts)

df.groupby("professional")["price"].mean()

professional
False    159.75
True     379.50
Name: price, dtype: float64

In [37]:
df.select_dtypes(include=['number']).corrwith(df["price"]).sort_values(ascending=False)

price                          1.000000
review_scores_value            0.885324
review_scores_rating           0.855834
review_scores_checkin          0.815572
review_scores_communication    0.808539
review_scores_location         0.804309
review_scores_accuracy         0.801605
review_scores_cleanliness      0.791116
listing_id                     0.120511
host_id                        0.114319
dtype: float64

In [38]:
(
    df.groupby(["neighbourhood_cleansed", "host_is_superhost"])["price"]
        .median()
        .unstack()
        .assign(diff=lambda x: x['t'] - x['f'])
)

host_is_superhost           f      t   diff
neighbourhood_cleansed
Beach                   157.5  390.0  232.5
Downtown                130.0  380.0  250.0
Old Town                127.5  410.0  282.5
Suburb                  175.0  400.0  225.0

In [39]:
df[["review_scores_rating", "review_scores_accuracy"]].corrwith(df["price"]).max().item()

0.8558342758472042

In [40]:
import pandas as pd

data = pd.read_csv("./mails.csv", delimiter="\t", on_bad_lines="skip")

In [42]:
df.isna()

,listing_id,host_id,host_is_superhost,neighbourhood_cleansed,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,professional
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False

In [44]:
for i in (1, 2, 3, 4)[:2]:
    print(i)

1
2

In [45]:
import numpy as np

In [47]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])

arr[0], arr[1:-1], arr[-1]

(np.int64(5), array([10, 15, 20]), np.int64(25))

In [61]:
arr = np.array([3, 6, 9, 12, 15, 18, 21])

print(arr[-3:])
print(arr[::2])
print(arr[::-1])
 
arr[np.where(arr == 12)] = 100
print(arr)

print(np.linspace(10, 50, 5))

[15 18 21]
[ 3  9 15 21]
[21 18 15 12  9  6  3]
[  3   6   9 100  15  18  21]
[10. 20. 30. 40. 50.]

In [ ]:
import numpy as np

arr = np.array([12, 7, 25, 18, 5, 30, 14])

print(arr[arr > 15])
print(arr[arr % 2 == 0])

arr[arr < 10] = 0

print(arr)

i dont know Count how many values are greater than 15.

print(arr.max(), arr.min())

[25 18 30]
[12 18 30 14]
[12  0 25 18  0 30 14]
30 0

In [85]:
arr = np.array([5, 8, 10, 3, 7, 12])

print(np.sum((arr % 2 != 0)))
print(arr[arr % 2 == 0].sum())
arr *= 5
print(arr)
arr[arr % 2 != 0] = -1
print(arr)

3
30
[25 40 50 15 35 60]
[-1 40 50 -1 -1 60]

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[1][1])
print(arr[1][:])
print(arr[:][2])
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=0))
arr[arr == 9] = 99

5
[4 5 6]
[7 8 9]
[ 6 15 24]

In [104]:
import numpy as np

arr = np.arange(1, 13)

_34 = np.reshape(arr, (3, 4))
_26 = np.reshape(arr, (2, 6))
_34.flatten()
_34.shape
arr.size
_34.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [113]:
import numpy as np

arr = np.array([4, 9, 16, 25, 36])

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.dot(b))

arr.sum(), arr.mean(), arr.max(), np.sqrt(arr), arr.std(), arr * 2

32

(np.int64(90),
 np.float64(18.0),
 np.int64(36),
 array([2., 3., 4., 5., 6.]),
 np.float64(11.436782764396638),
 array([ 8, 18, 32, 50, 72]))

In [133]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(
    np.concat((a, b)),
    np.vstack((a, b)), 
    np.hstack((a, b))
)

arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))

np.linspace(0, 1, 12).reshape((3, 4)).flatten()

[1 2 3 4 5 6] [[1 2 3]
 [4 5 6]] [1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [135]:
np.random.ranf(5), np.random.randint(0, 100, 10)

(array([0.52279332, 0.16637168, 0.55835186, 0.53770366, 0.07664427]),
 array([12,  3,  6, 83, 30, 45, 77, 57, 64, 71], dtype=int32))

In [137]:
arr = np.array([10, 20, 30, 40, 50])

np.random.choice(arr, 3)

array([10, 10, 40])

In [138]:
np.random.seed(42)

In [139]:
arr = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr)

In [140]:
arr

array([2, 5, 3, 1, 4])

In [ ]:
import numpy as np

arr = np.array([12, 5, 18, 7, 25, 30, 9, 16])

print(np.where(arr > 15))

arr[arr % 2 == 0] = 0

arr = np.array([12, 5, 18, 7, 25, 30, 9, 16])

print(np.sort(arr))

np.unique(np.array([1, 2, 2, 3, 3, 3, 4, 4])), np.argmax(arr)

(array([2, 4, 5, 7]),)
[ 5  7  9 12 16 18 25 30]

np.int64(5)

In [150]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])